routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

Route::get('thanks/member-fee/paypal', 'App\Http\Controllers\ThanksController@paidMemberFeeViaPayPal')->name('thanks.member-fee.paypal');
Route::get('thanks/donation/paypal', 'App\Http\Controllers\ThanksController@paidDonationViaPayPal')->name('thanks.donation.paypal');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {

    // Allow to easily preview some internal pages without the need of complicated reproduce steps.
    Route::get('demo/oauth/authorize',
        [App\Http\Controllers\Dev\Demos::class, 'oauthAuthorize']
    )->name('dev.preview.oauth.authorize');

    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/unpartecipate/{assembly_id}', 'AssemblyController@unpartecipate')->name('assembly.unpartecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

// Useful public pages
Route::get('page/how-to-pay', 'PageController@howToPay')->name('page.how-to-pay');

app/Http/Controllers/AssemblyController.php
<?php

namespace App\Http\Controllers;

use App\Assembly;
use App\AssemblyUser;
use App\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AssemblyController extends EditController
{
    public function __construct()
    {
        parent::init([
            'classname' => Assembly::class,
            'view_folder' => 'assembly'
        ]);
    }

    protected function requestToObject(Request $request, $object): void
    {
        // The EditController already protects the "edit" action calling AssemblyPolicy#edit().

        $fields = ['date', 'status', 'announce'];
        $this->fitObject($object, $fields, $request);
    }

    protected function defaultValidations($object)
    {
        return [
            'date' => 'required',
            'status' => 'required|in:pending,open,closed',
            'announce' => 'required',
        ];
    }

    protected function defaultSortingColumn()
    {
        return 'date';
    }

    protected function defaultSortingDirection()
    {
        return 'desc';
    }

    /**
     * @return array
     */
    protected function getEditArguments($id)
    {
        $data = parent::getEditArguments($id);

        // Get the current Assembly.
        $assembly = $data['object'];

        // Get the users that are participating (with or without delegation).
        $data['assembly_users'] =
            $assembly
                ->users()
                ->orderByUserPrintableName()
//              ->chaperone()      // Micro-optimization for N+1 problem on Assembly. TODO: adopt this to replace setAttribute() after Laravel 11.22.
                ->with('user')     // Micro-optimization for N+1 problem on AssemblyUser.user
                ->with('delegate') // Micro-optimization for N+1 problem on AssemblyUser.delegate
                ->get();

        // Micro-optimization for N+1 problem on Assembly.
        // TODO: use just chaperone() after we upgrade to Laravel 11.22.
        foreach ($data['assembly_users'] as $assembly_user) {
            $assembly_user->setAttribute('assembly', $assembly);
        }

        // Check if the current user is somehow participating (with or without delegation).
        // Micro-optimization: we avoid a query by just filtering previous results.
        $data['user_participation'] =
            $data['assembly_users']
                ->filter( function ($assembly_user) use (&$data) {
                    if ($assembly_user->user->id === Auth::user()->id) {
                        return $assembly_user->user;
                    }
                } )
                ->first();

        // Check if the current user has delegated to somebody else. Get that somebody else.
        $data['user_voting_for_me'] = $data['user_participation']->delegate ?? null;

        return $data;
    }

    /**
     * Add myself as direct participant (and potential voter) in one Assembly.
     */
    public function partecipate(Request $request, $assembly_id)
    {
        // Get the Assembly, or page not found.
        $assembly = Assembly::findOrFail($assembly_id);

        // Make sure you have enough permissions to append your participation in this Assembly,
        // calling AssemblyPolicy#participate().
        // Do not allow to participate in closed assemblies, etc.
        $this->authorize('participate', $assembly);

        // Update everything, or rollback everything on error.
        DB::transaction(function () use ($request, $assembly) {
            // Cleanup my (old?) direct participation and my delegation(s) (if any).
            $this->removeDirectParticipationIfAuthorized($request, $assembly);
            $this->removeDelegationsAssignedToMeIfAuthorized($request, $assembly);

            // Add my direct participation.
            // Delegate my vote to the selected user.
            $delegate = new AssemblyUser;
            $delegate->assembly_id = $assembly->id;
            $delegate->user_id = Auth::user()->id;
            $delegate->delegate_id = 0; // TODO: make 'delegate_id' nullable.
            $delegate->save();
        });

        // Return back to the single Assembly.
        return redirect()->route('assembly.show', $assembly_id);
    }

    /**
     * Remove myself as participant in one Assembly,
     * eventually nuking the delegations on myself.
     */
    public function unpartecipate(Request $request, $assembly_id)
    {
        // Get the Assembly, or page not found.
        $assembly = Assembly::findOrFail($assembly_id);

        // Update everything, or rollback everything on error.
        DB::transaction(function () use ($request, $assembly) {
            // Detach my direct participation and my delegation(s),
            // only if I'm authorized, if the assembly is not closed, etc.
            $this->removeDirectParticipationIfAuthorized($request, $assembly);
            $this->removeDelegationsAssignedToMeIfAuthorized($request, $assembly);
        });

        // Return back to the single Assembly.
        return redirect()->route('assembly.show', $assembly_id);
    }

    public function delegate(Request $request, $assembly_id, $delegate_id)
    {
        // Get the Assembly and the target User, or page not found.
        $assembly = Assembly::findOrFail($assembly_id);
        $delegate_user = User::findOrfail($delegate_id);

        // Make sure you have enough permissions to set your delegation in this Assembly,
        // calling AssemblyPolicy#delegate().
        $this->authorize('delegate', [$assembly, $delegate_user]);

        // Update everything, or rollback everything on error.
        DB::transaction(function () use ($request, $assembly, $delegate_user) {
            // First, remove my direct participation, if any,
            // only if I'm authorized, if the assembly is not closed, etc.
            $this->removeDirectParticipationIfAuthorized($request, $assembly);

            // Delegate my vote to the selected user.
            $delegate = new AssemblyUser;
            $delegate->assembly_id = $assembly->id;
            $delegate->user_id = Auth::user()->id;
            $delegate->delegate_id = $delegate_user->id;
            $delegate->save();
        });

        // Return back to the single Assembly.
        return redirect()->route('assembly.show', $assembly_id);
    }

    public function undelegate(Request $request, $assembly_id)
    {
        // Get the Assembly, or page not found.
        $assembly = Assembly::findOrFail($assembly_id);

        // Make sure you have enough permissions to remove my delegation,
        // calling AssemblyPolicy#undelegate.
        $this->authorize('undelegate', $assembly);

        // Update everything, or rollback everything on error.
        DB::transaction(function () use ($request, $assembly) {
            $this->removeDirectParticipationIfAuthorized($request, $assembly);
        });

        // Return back to the single Assembly.
        return redirect()->route('assembly.show', $assembly_id);
    }

    /**
     * Drop my direct participation, if set, if I'm authorized to so so.
     * This method does NOT open a transaction.
     * You may want to manually do it.
     */
    private function removeDirectParticipationIfAuthorized(Request $request, Assembly $assembly)
    {
        // Make sure you have enough permissions to append your participation in this Assembly,
        // calling AssemblyPolicy#unparticipate().
        $this->authorize('unparticipate', $assembly);

        // Drop my direct participation (if any).
        $assembly->users()->whereUserIsMe()->delete();
    }

    /**
     * Drop my delegations (people who delegated to me), if any, if I'm authorized to do so.
     * This method does NOT open a transaction.
     * You may want to manually do it.
     */
    private function removeDelegationsAssignedToMeIfAuthorized(Request $request, Assembly $assembly)
    {
        // Make sure you have enough permissions to append your participation in this Assembly,
        // calling AssemblyPolicy#unparticipate().
        $this->authorize('undelegate', $assembly);

        // Drop all the delegations I have (if any).
        $assembly->users()->whereDelegateUserIsMe()->delete();
    }
}

resources/views/assembly/edit.blade.php
@php
$assembly = $object;
@endphp

@extends('layouts.app')

@section('content')
<div class="container">

    <h2>{{ $assembly->title }}</h2>

    @if ($assembly->isOpen() || $assembly->isPending())
    @cannot('proveRightToVote', \App\Assembly::class)
        <div class="alert alert-warning" role="alert">
            Non hai i requisiti di voto per votare in un'assemblea.
        </div>
    @endcannot
    @endif

    @if ($assembly->isPending())
        <div class="alert alert-info" role="alert">
            Questa assemblea non è ancora aperta. Probabilmente è ancora presto.
        </div>
    @elseif ($assembly->isClosed())
        @can('update', $assembly)
            <div class="alert alert-warning" role="alert">
                Questa è un'assemblea conclusa. In qualità di amministratore, puoi modificarla ma solo se sai cosa stai facendo (e.g. per correggere ovvi refusi).
            </div>
        @else
            <div class="alert alert-info" role="alert">
                Questa è un'assemble conclusa.
            </div>
        @endcan
    @endif

                    <div class="card">
                        <div>
                            <div class="card-body">
                                <div class="row">

                                    <div class="col-md-6">

                                        @include('assembly.votations', ['assembly' => $assembly])

                                        @can('update', $assembly)
                                            <form method="POST" action="{{ route('assembly.update', $assembly->id) }}">
                                                @method('PUT')
                                                @csrf

                                                @include('assembly.form', ['object' => $assembly])

                                                <div class="form-group row">
                                                    <div class="col-sm-10">
                                                        <button type="submit" class="btn btn-primary">Salva</button>
                                                    </div>
                                                </div>
                                            </form>

                                            <hr>

                                            @include('assembly.managevotations', ['assembly' => $assembly])
                                        @else
                                            <p>
                                                {!! $assembly->announceRendered !!}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="col-md-6">
                                        @can('participate', $assembly)
                                            <div class="row mb-3">
                                                <div class="col-md-12">
                                                    <p>Per poter votare in questa assemblea devi segnalare la tua partecipazione oppure delegare un'altra persona. Se si vuole delegare ma non si può partecipare alla assemblea si può revocare la partecipazione e assegnare la delega.</p>
                                                    @if ($user_participation)
                                                        <form method="POST" action="{{ route('assembly.unpartecipate', $assembly->id) }}">
                                                            @csrf
                                                            <button type="submit" class="btn btn-danger {{ Auth::user()->can('unparticipate', $assembly) ? '' : 'disabled' }}">Revoca Partecipazione</button>
                                                            <!-- We don't do security through obscurity. The button is always here. Backend is secure. -->
                                                        </form>
                                                    @else
                                                        <form method="POST" action="{{ route('assembly.partecipate', $assembly->id) }}">
                                                            @csrf
                                                            <button type="submit" class="btn btn-primary {{ Auth::user()->can('participate', $assembly) ? '' : 'disabled' }}">Segnala Partecipazione</button>
                                                            <!-- We don't do security through obscurity. The button is always here. Backend is secure. -->
                                                        </form>
                                                    @endif
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p>Partecipanti totali: <b>{{ count($assembly->users) }}</b></p>
                                                    <ul class="list-group">
                                                        @foreach ($assembly_users as $participant)
                                                            <li class="list-group-item">
                                                                {{ $loop->iteration }} &middot;

                                                                @can('update', $participant)
                                                                   <a href="{{ route('user.edit', $participant->user_id) }}" target="_blank">
                                                                   {{ $participant->user->printableName }}
                                                                   </a>
                                                                @else
                                                                   {{ $participant->user->printableName }}
                                                                @endcan

                                                                @if (!$user_participation && Auth::user()->can('delegate', [ $assembly, $participant->user ]))
                                                                    <form method="POST" action="{{ route('assembly.delegate', ['assembly_id' => $assembly->id, 'delegate_id' => $participant->user_id]) }}" class="float-right">
                                                                        @csrf
                                                                        <button type="submit" class="btn">Delega</button>
                                                                    </form>
                                                                @elseif($participant->delegate)
                                                                    tramite delega a
                                                                    @can('update', $participant->delegate)
                                                                        <a href="{{ route('user.edit', $participant->delegate->id) }}" target="_blank">
                                                                            {{ $participant->delegate->printableName }}
                                                                        </a>
                                                                    @else
                                                                        {{ $participant->delegate->printableName }}
                                                                    @endcan
                                                                @endif

                                                                @if (!$assembly->isClosed())
                                                                <div>
                                                                    @include( 'assembly/vote-capability-badges', [
                                                                        'participant' => $participant,
                                                                        'assembly' => $assembly,
                                                                    ] )
                                                                </div>
                                                                @endif
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </div>
                                            </div>
                                        @else
                                            <!-- Else: you cannot participate. -->
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <h3>Presenze</h3>
                                                    <ul class="list-group">
                                                        @foreach ($assembly_users as $participant)
                                                            <li class="list-group-item">
                                                                {{ $loop->iteration }} &middot; {{ $participant->user->printableName }}

                                                                @if ($participant->delegate)
                                                                    tramite delega a {{ $participant->delegate->printableName }}
                                                                @endif

                                                                @if (!$assembly->isClosed())
                                                                <div>
                                                                    @include( 'assembly/vote-capability-badges', [
                                                                        'participant' => $participant,
                                                                        'assembly' => $assembly,
                                                                    ] )
                                                                </div>
                                                                @endif
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </div>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
    </div>
</div>
@endsection

resources/views/assembly/form.blade.php
<div class="form-group row">
    <label for="assembly-date" class="col-sm-4 col-form-label">Data</label>
    <div class="col-sm-8">
        <input type="date" class="form-control" name="date" id="assembly-date" value="{{ $object ? $object->date->format('Y-m-d') : '' }}" required>
    </div>
</div>

<div class="form-group row">
    <label for="assembly-status" class="col-sm-4 col-form-label">Stato</label>
    <div class="col-sm-8">
        <select class="form-control" name="status" id="assembly-status" autocomplete="off" required>
            <option value="pending" @selected( $object && $object->status === 'pending' )>In Attesa</option>
            <option value="open" @selected( $object && $object->status === 'open' )>Aperta</option>
            <option value="closed" @selected( $object && $object->status === 'closed' )>Chiusa</option>
        </select>
    </div>
</div>

<div class="form-group">
    <label for="assembly-announce" class="col-sm-4 col-form-label">Convocazione</label>
    <div class="col-sm-12">
        <textarea class="form-control" name="announce" id="assembly-announce" rows="10" width="100%" required>{{ $object ? $object->announce : '' }}</textarea>
    </div>
</div>

resources/views/assembly/managevotations.blade.php
@if($assembly->status != 'closed')
    @foreach($assembly->votations as $votation)
        <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editVotation{{ $votation->id }}">Edita Votazione: {{ substr($votation->question, 0, 20) }}...</button>
        </p>

        <div class="modal fade" id="editVotation{{ $votation->id }}" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modifica Votazione</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <form method="POST" action="{{ route('votation.update', $votation->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="modal-body">
                            @include('votation.form', ['object' => $votation])
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                            <button type="submit" class="btn btn-primary">Salva</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach
@endif

@can('addVotation', $assembly)
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createVotation">Nuova Votazione</button>
    <div class="modal fade" id="createVotation" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Nuova Votazione</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <form method="POST" action="{{ route('votation.store') }}">
                    @csrf
                    <div class="modal-body">
                        @include('votation.form', ['object' => null, 'assembly_id' => $assembly->id])
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endcan

resources/views/assembly/vote-capability-badge.blade.php
@if ($user->can('proveRightToVote', $assembly))
    <span class="badge badge-info">✅ {{ $userRoleLabel }} ha diritto di voto</span>
@else
    <span class="badge badge-danger">❌ {{ $userRoleLabel }} non ha diritto di voto</span>
@endif