routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

Route::get('thanks/member-fee/paypal', 'App\Http\Controllers\ThanksController@paidMemberFeeViaPayPal')->name('thanks.member-fee.paypal');
Route::get('thanks/donation/paypal', 'App\Http\Controllers\ThanksController@paidDonationViaPayPal')->name('thanks.donation.paypal');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {

    // Allow to easily preview some internal pages without the need of complicated reproduce steps.
    Route::get('demo/oauth/authorize',
        [App\Http\Controllers\Dev\Demos::class, 'oauthAuthorize']
    )->name('dev.preview.oauth.authorize');

    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/unpartecipate/{assembly_id}', 'AssemblyController@unpartecipate')->name('assembly.unpartecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

// Useful public pages
Route::get('page/how-to-pay', 'PageController@howToPay')->name('page.how-to-pay');

app/Movement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

use DB;
use Exception;

use App\AccountRow;
use App\Config;

/**
 * A Movement is a money transfer from (or to) your bank account(s).
 * A Movement may create AccountRow(s).
 * Each Movement may generate a single Receipt.
 */
class Movement extends Model
{

    use ILSModel;

    /**
     * Get the attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
    ];

    /**
     * Toggle validation of each AccountRows(s). from the validate() method.
     * As default we validate each of them.
     */
    private bool $validateEachAccountRow = true;

    /**
     * Toggle validation of AccountRows(s) from the validate() method.
     * As default we validate their sum.
     */
    private bool $validateAllAccountRows = true;

    public function getEntityNameSingular(): string
    {
        return 'Movimento';
    }

    public function getEntityNamePlural(): string
    {
        return 'Movimenti';
    }

    public function bank()
    {
        return $this->belongsTo('App\Bank');
    }

    public function account_rows()
    {
        return $this->hasMany('App\AccountRow')->with('user');
    }

    public function receipt()
    {
        return $this->hasOne('App\Receipt');
    }

    public function refund()
    {
        return $this->hasMany('App\Refund');
    }

    /**
     * Scope a query to only include movements related to an Unicredit bank.
     */
    public function scopeUnicredit(Builder $query): void
    {
        $query->whereHas('bank', function ($bank_query) {
            $bank_query->unicredit();
        });
    }

    public function getAmountFormattedAttribute(): string
    {
        return format_amount( $this->amount );
    }

    public function getAmountOriginalFormattedAttribute(): string
    {
        return format_amount( $this->amount_original );
    }

    public function getAmountOriginalOrAnyFormattedAttribute(): string
    {
        return format_amount( $this->amount_original ?? $this->amount );
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('accounting/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] === '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    /**
     * Get the year of this Movement's date.
     *
     * @return int Year of the date
     */
    public function getDateYearAttribute()
    {
        if( !$this->date ) {
            throw new \Exception("No date, no party");
        }
        return (int) substr($this->date, 0, 4);
    }

    /**
     * Get the already-imported Movement with big margin of confidence.
     * The confidence is low on Unicredit, since there, we historically had no identifier.
     * You may want to then also run Movement#isExactlySameMovement($other) to be 100% sure.
     * @return Movement|null
     */
    public function alreadyTrackedMovement()
    {
        $query = Movement::query();

        // Skip myself if I'm already persisted.
        if (!empty($this->id))
        {
            $query = $query->where('id', '<>', $this->id);
        }

        // Base condition. Look for the copy of myself under the same bank.
        $query = $query->where('bank_id', $this->bank_id);

        // If the bank+identifier is available, use just these robust info.
        if (!empty($this->identifier))
        {
              $query = $query->where('identifier', $this->identifier);
        }
        else
        {
            // No identifier. Do desperate things.
            // Pitfall: Unicredit randomly changes "notes"...
            $query = $query->where('date', $this->date)
                           ->where('amount', $this->amount)
                           ->where('notes', $this->notes);
        }

        return $query->first();
    }

    /**
     * Check if this (non-persisted) Movement was already imported.
     * @return bool
     */
    public function alreadyTracked()
    {
        return !is_null( $this->alreadyTrackedMovement() );
    }

    /**
     * Check whenever two Movements are really the same thing.
     * This is supposed to check for everything, but the id.
     * @param Movement
     * @return bool
     */
    public function isExactlySameMovement($other)
    {
        // Limit days of difference between the two movements.
        // It happened to have a PayPal movement imported as 2024-01-09 but then moved
        // from PayPal to 2023-12-29, so, in a different year, with same identifier. lol
        $max_days_diff = 30;

        // The identifier is supposed to be unique for the whole history of the bank
        // for myself as customer.
        // This seems untrue for PayPal, that has API errors if you try to download
        // a specific Transaction ID without a date. So I guess the identifier
        // is probably unique by year :) So this is a reasonable strong check.
        return $this->bank_id    ==  $other->bank_id
            && !is_null($this->identifier)
            && $this->identifier === $other->identifier
            && $this->date->diffInDays($other->date) < $max_days_diff;
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }

    /**
     * Append some proposed AccountRow(s) covering membership fees.
     * This method tries to update already-existing AccountRow(s).
     * To recognize which of them were created, loop your "account_rows"
     * and look for ones without an "id" or with "edited".
     * @return boolean
     */
    public function proposeMembershipFeesForUser($user)
    {
        if (!is_object($user)) {
            $user_id = $user;
            $user = User::find($user_id);
            if (is_null($user)) {
                Log::error('Errore nel riconoscimento utente di cui generare le quote di iscrizione: ' . $user_id);
                return false;
            }
        }

        $fees_account = Config::feesAccount();
        $donations_account = Account::where('donations', true)->first();
        $year = $user->firstMissingFeeYear();

        // First, try expanding an already-existing stub AccountRow.
        $already_existing_ar = $this->findStubAccountRow();
        $ar = $already_existing_ar;
        if ($ar) {
            $amount = $ar->amount;
        } else {
            $amount = $this->getAccountRowsAmountDiffError();
        }

        while($amount >= $user->feeAmount) {
            // Add a new AccountRow or expand the initial one.
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $fees_account->id;
            $ar->amount = $user->feeAmount;
            $ar->user_id = $user->id;
            $ar->notes = AccountRow::createFeeNote($user, $year);
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }

            $amount = bcsub($amount, $user->feeAmount, 2);
            $year++;

            // Force the creation of a new AccountRow on the next run.
            $ar = null;
        }

        if ($amount > 0) {
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $donations_account->id;
            $ar->amount = $amount;
            $ar->notes = sprintf('Donazione da parte di %s', $user->printable_name);
            $ar->user_id = $user->id;
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }
        }

        return true;
    }

    /**
     * Find the most recent Account Row from the whole history, using a generic note
     *
     * @param string $guess_by_note
     * @return AccountRow
     */
    public function proposeAccountRowFromHistory($guess_by_note)
    {
        // Get the already-saved AccountRow's Account IDs.
        // This is useful since probably we wont to import what remains.
        $current_account_ids = $this->account_rows->pluck('account_id');

        $prev_movement_query = Movement::query()
          ->where('notes', 'like', $guess_by_note)
          ->whereHas('account_rows', function($query) use ($current_account_ids) {
              if ($current_account_ids) {
                  $query->whereNotIn('account_id', $current_account_ids);
              }
          })
          ->orderBy('id', 'desc');

        // Do not suggest myself.
        if ($this->id) {
            $prev_movement_query->whereNot('id', $this->id);
        }

        $prev_movement = $prev_movement_query->first();
        if ($prev_movement) {
            $prev_account_row = $prev_movement->account_rows()->first();
            if ($prev_account_row) {
                $remaining_amount = $this->getAccountRowsAmountDiffError();
                $remaining_plus_fee = bcadd($remaining_amount, $prev_account_row->amount, 2);
                if ($remaining_plus_fee > 0) {
                    $ar = new AccountRow;
                    $ar->movement_id = $this->id;
                    $ar->account_id = $prev_account_row->account_id;
                    $ar->user_id = $prev_account_row->user_id;
                    $ar->section_id = $prev_account_row->section_id;
                    $ar->notes = $prev_account_row->notes;
                    $ar->amount = $prev_account_row->amount;

resources/views/movement/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-9">

                @foreach(App\Bank::orderBy('name')->where('type', '<>', 'paypal')->get() as $bank)
                    <!-- start form upload movements file -->
                    <form class="form" method="post" action="{{ route('movement.store') }}" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="store_from" value="file" />
                        <input type="hidden" name="bank_id" value="{{ $bank->id }}" />

                        <div class="form-group">
                            <p>Import da file <b>{{$bank->name}}</b> (ultimo aggiornamento: <a href="{{ route('movement-detailed.index') }}?bank_id={{ $bank->id }}&year={{ $year }}&with_account_rows=on&order_dir=desc" target="_blank">{{ $bank->last_update }}</a>):</p>
                            <p><input type="file" name="file" /></p>
                            <p><button type="submit" class="btn btn-primary">Importa File {{ $bank->name }}</button></p>
                        </div>
                    </form>
                    <hr />
                    <!-- end form upload movements file -->
                @endforeach

                <!-- start form PayPal API -->
                @if(PayPalAPIMovementsReader::hasValidConfig())
                    <form class="form" method="post" action="{{ route('movement.store') }}">
                        @csrf
                        <input type="hidden" name="store_from" value="paypal_api" />

                        <div class="form-group row">
                            <label for="date-from" class="col-sm-4 col-form-label">Da (opzionale)<br /><small>default: giorno prima dell'ultimo movimento</small></label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" name="date_from" id="date-from" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="date-to" class="col-sm-4 col-form-label">A (opzionale)<br /><small>default: oggi</small></label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" name="date_to" id="date-to" />
                            </div>
                        </div>

                        <!--
                        If you want to use this thing, also decomment snippet from app/Actions/ImportPayPalMovements.php
                        <div class="form-group row">
                            <label for="debug-superlol-activator" class="col-sm-4 col-form-label">Attivare Debug Cosmico? (utile per generare unit test)</label>
                            <div class="col-sm-8">
                                <input type="checkbox" class="form-control" name="debug_superlol_activator" id="debug-superlol-activator" />
                            </div>
                        </div>
                        -->

                        <button type="submit" class="btn btn-primary">Importa da API PayPal</button>
                    </form>
                @endif
                <!-- end form PayPal API -->

            </div>
            <div class="col-md-3">
                @include('movement.reviewcounter')
            </div>
        </div>

        <hr>

        <nav class="nav mt-3">
            @foreach(App\Movement::selectRaw('YEAR(date) as year')->distinct()->orderBy('year', 'asc')->pluck('year') as $nav_year)
                <a class="nav-link{{ $year == $nav_year ? ' active font-weight-bold' : '' }}"
                   href="{{ route('movement.index', ['year' => $nav_year, 'user_id' => request('user_id'), 'section_id' => request('section_id')]) }}">
                    {{ $nav_year }}
                </a>
            @endforeach
        </nav>

        <form action="{{ route('movement.index') }}" method="get" class="form-inline mt-3">
            <input type="hidden" name="year" value="{{ request('year', date('Y')) }}">
            <div class="form-group mb-2">
                <label for="user_id">Socio:</label>
                <select class="form-control mx-sm-3" name="user_id" id="user_id">
                    <option value="">Tutti</option>
                    @foreach($users as $user)
                        <option value="{{ $user->id }}"{{ request('user_id') == $user->id ? ' selected' : '' }}>{{ $user->printableName }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group mb-2">
                <label for="section_id">Sezione Locale:</label>
                <select class="form-control mx-sm-3" name="section_id" id="section_id">
                    <option value="">Tutte</option>
                    @foreach($sections as $section)
                        <option value="{{ $section->id }}"{{ request('section_id') == $section->id ? ' selected' : '' }}>{{ $section->city }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Filtra</button>
        </form>

        <canvas id="chart"></canvas>

        <div class="row mt-3">
            <div class="col-md-12">
                <h2>Riepilogo Entrate/Uscite {{$year}}</h2>
                {!! $financialSummary->render() !!}
            </div>
        </div>

        @php
            // Find banks without an initial movement for this year, to quickly create them.
            $banks_without_start_of_year = App\Bank::query()
              ->whereDoesntHave('movements', function( $query ) use ( $year ) {
                $query->where('start_of_year', $year);
              } )
              ->get();
        @endphp
        @if (!$banks_without_start_of_year->isEmpty())
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2>Creazione Saldo Iniziale 1 gennaio {{ $year }}</h2>
                    <p>Non è noto il saldo iniziale al 1 gennaio {{ $year }}. Inserisci ora i relativi dati:</p>
                    @foreach ($banks_without_start_of_year as $bank_without_start_of_year)
                        <p><a href="{{ route( 'movement.create', [
                            'bank_id'       => $bank_without_start_of_year->id,
                            'date'          => "$year-01-01",
                            'notes'         => sprintf( "Saldo iniziale al 1 gennaio %d in %s", $year, $bank_without_start_of_year->name ),
                            'start_of_year' => $year,
                       ] ) }}" class="btn btn-secondary">Crea Saldo Iniziale {{ $year }} in {{ $bank_without_start_of_year->name }}</a></p>
                    @endforeach
                </div>
            </div>
        @endif

        @php
            // Find start of year special movements.
            $movements_with_start_of_year = App\Movement::query()
              ->where('start_of_year', $year)
              ->get();
        @endphp
        @if (!$movements_with_start_of_year->isEmpty())
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2>Saldo Iniziale 1 gennaio {{ $year }}</h2>
                    <p>I seguenti movimenti rappresentano il saldo iniziale al 1 gennaio {{ $year }} nei rispettivi conti correnti:</p>
                    <table class="table dataTable">
                        <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Cassa</th>
                            <th>Saldo Iniziale</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($movements_with_start_of_year as $movement_with_start_of_year)
                            <tr>
                                <td><a href="{{ route( 'movement.edit', $movement_with_start_of_year->id ) }}"><i class="fa-solid fa-pencil"></i></a></td>
                                <th>{{ $movement_with_start_of_year->bank->name }}</th>
                                <td>{{ $movement_with_start_of_year->amount_formatted }} EUR</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endif

        <div class="row mt-4">
            <div class="col-md-12">
                <h2>Dettagli Entrate/Uscite {{$year}}</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Data</th>
                        <th>Valore</th>
                        <th>Account</th>
                        <th>Note</th>
                        <th>Visualizza</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($objects as $row)
                        <tr class="{{
                          $row->movement->start_of_year
                            ? 'table-secondary'
                            : (($row->amount_in > 0)
                                ? 'table-success'
                                : 'table-danger')
                        }}">
                            <td>{{ $row->movement->date }}</td>
                            <td>{{ $row->amount_formatted }}</td>
                            <td>{{ $row->account ? $row->account->printable_name : 'Utente non definito' }}</td>
                            <td>{{ $row->notes }}</td>
                            <td><a href="{{ route('movement.edit', $row->movement->id) }}"><i class="fa-solid fa-pencil"></i></a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <script>
        const labels = ['saldo iniz.', 'gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'];
        const data = {
            labels: labels,
            datasets: [
                {
                    label: 'Entrate reali',
                    data: @json( array_values($real_incomes) ),
                    borderColor: '#00aa00',
                    backgroundColor: 'rgba(50, 170, 50, 0.8)',
                },
                {
                    label: 'Entrate previste',
                    data: @json( array_values($forecast_incomes) ),
                    borderColor: '#00aa00',
                    backgroundColor: 'rgba(50, 170, 50, 0.3)',
                },
                {
                    label: 'Uscite reali',
                    data: @json( array_values($real_costs) ),
                    borderColor: '#aa0000',
                    backgroundColor: 'rgba(190, 30, 30, 0.8)',
                },
                {
                    label: 'Uscite previste',
                    data: @json( array_values($forecast_costs) ),
                    borderColor: '#aa0000',
                    backgroundColor: 'rgba(190, 30, 30, 0.3)',
                },
                {
                    label: 'Saldo reale',
                    data: @json( array_values($real_revenue) ),
                    borderColor: '#4490e7',
                    type: 'line',
                    borderDash: [20, 20],
                    backgroundColor: 'rgba(14, 45, 81, 0.4)',
                },
                {
                    label: 'Saldo previsto',
                    display: false,
                    data: @json( array_values($forecast_revenue) ),
                    borderColor: '#4490e755',
                    type: 'line',
                    borderDash: [20, 20],
                    backgroundColor: 'rgba(14, 45, 81, 0.1)',
                }
            ]
        };

        const config = {
            type: 'bar',
            data: data,
            options: {
                responsive: true
            },
        };

        addEventListener("DOMContentLoaded", (event) => {
            const ctx = document.getElementById('chart');

            new Chart(ctx, config);
        });

    </script>
@endsection

resources/views/movement/reviewcounter.blade.php
@php
$un_reviewed_movements = App\Movement::where('reviewed', 0)->count();
@endphp
@if($un_reviewed_movements)
    <a href="{{ route('movement.review') }}" class="btn btn-primary float-right">{{ $un_reviewed_movements }} Movimenti da Revisionare</a>
@endif